EasyWord/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flashcards.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

flashcards/urls.py
from django.urls import path
from . import views

app_name = "flashcards"

urlpatterns = [
    path('', views.index, name="index"),
    path('dictionary/', views.dictionary, name="dictionary"),
    path('register/', views.RegisterUser.as_view(), name="register"),
    path('login/', views.LoginUser.as_view(), name="login"),
    path('logout/', views.logout_user, name="logout_user"),
    path('learn/', views.learn, name="learn"),
    path('repeat/', views.repeat, name="repeat"),
]

flashcards/models.py
from django.db import models
from django.contrib.auth.models import User


class EnglishWords(models.Model):
    word = models.CharField(max_length=20)
    translation = models.CharField(max_length=35)
    level = models.CharField(max_length=2)
    audio_link = models.CharField(max_length=130)
    phonetics = models.CharField(max_length=25, blank=True)
    example = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return f"{self.word}: {self.translation}"


class UserWordSelection(models.Model):
    STATUS_CHOICES = [
        ("selected", "Selected"),    # user can start to learn this word
        ("learning", "Learning"),    # user currently learning this word
        ("known", "Already known"),  # user already know this word
        ("repeating", "Repeating"),  # user learned this word and now repeating it
        ("learned", "Fully learned") # user learned this word and repeated it
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    english_words = models.ForeignKey(EnglishWords, on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default="selected")


class RepeatWord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    english_words = models.ForeignKey(EnglishWords, on_delete=models.CASCADE)
    date = models.DateTimeField()
    # a word needs to be repeated multiple times to be considered fully learned
    times_repeated = models.PositiveSmallIntegerField(default=0)

flashcards/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
    # add label, placeholder, class for form fields
    username = forms.CharField(label="Ім'я користувача:", widget=forms.TextInput(attrs={"placeholder": "Ім'я користувача", "class": "form-control"}))
    email = forms.EmailField(label="Email адреса:", required=True, widget=forms.TextInput(attrs={"placeholder": "Email адреса", "class": "form-control"}))  # field email is required
    password1 = forms.CharField(label="Пароль:", widget=forms.PasswordInput(attrs={"placeholder": "Пароль", "class": "form-control"}))
    password2 = forms.CharField(label="Підтвердження пароля:", widget=forms.PasswordInput(attrs={'placeholder': "Підтвердження пароля", "class": "form-control"}))


    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class AuthenticationUserForm(AuthenticationForm):
    username = forms.CharField(label="Ім'я користувача:", widget=forms.TextInput(attrs={"placeholder": "Ім'я користувача","class": "form-control"}))
    password = forms.CharField(label="Пароль:", widget=forms.PasswordInput(attrs={"placeholder": "Пароль", "class": "form-control"}))

flashcards/views.py
from calendar import month

from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.http import JsonResponse
from datetime import timedelta
from .forms import *
from .models import *
import json
from django.utils import timezone
from django.db.models import F


def index(request):
    return render(request, "flashcards/index.html")

def dictionary(request):
    paginator = Paginator(EnglishWords.objects.all(), 60)
    page = request.GET.get("page")
    english_words = paginator.get_page(page)

    # get indexes of next 2 and previous 2 pages for pagination
    current_page = english_words.number
    start_page_range = max(current_page - 2, 2)
    end_page_range = min(current_page + 3, paginator.num_pages)
    page_range = range(start_page_range, end_page_range)

    context = {"english_words": english_words, "page_range": page_range}
    return render(request, "flashcards/dictionary.html", context)


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = "flashcards/register.html"
    success_url = reverse_lazy("flashcards:index")

    def form_valid(self, form):
        user = form.save() # add new user to database

        # mark all words as selected for this user
        english_words = EnglishWords.objects.all()
        data = []
        for word in english_words:
            data.append(UserWordSelection(user=user, english_words=word))
        UserWordSelection.objects.bulk_create(data)

        login(self.request, user) # auto login
        return redirect("flashcards:index")


class LoginUser(LoginView):
    form_class = AuthenticationUserForm
    template_name = "flashcards/login.html"

    def get_success_url(self):
        return reverse_lazy("flashcards:index")


def logout_user(request):
    logout(request)
    return redirect("flashcards:login")

@login_required # if user is not authenticated - page 404
def learn(request):
    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
    if is_ajax:
        # GET request is used for sending data to js file
        if request.method == "GET":
            # get words with status "learning" from db
            learning_words = list(EnglishWords.objects.filter(userwordselection__user=request.user, userwordselection__status="learning").order_by("?").values())
            # get words with status "selected" from db
            number_of_selected_words = 10 - len(learning_words) # total number of words is 10
            # variable sometimes can be negative because of race condition between AJAX requests
            if number_of_selected_words < 0:
                number_of_selected_words = 0
            selected_words = list(EnglishWords.objects.filter(userwordselection__user=request.user, userwordselection__status="selected").order_by("?").values()[:number_of_selected_words])

            context = {
                "selected_words": selected_words,
                "learning_words": learning_words
            }
            return JsonResponse(context)  # send words to js file
        # POST request is used for getting data from js file
        if request.method == "POST":
            data = json.loads(request.POST.get("main"))
            # update word status
            UserWordSelection.objects.filter(user=request.user, english_words=data["word_id"]).update(status=data["status"])

            if data["status"] == "repeating":
                word = EnglishWords.objects.get(id=data["word_id"])
                RepeatWord.objects.create(user=request.user, english_words=word, date=timezone.now())
            return JsonResponse({"status": "success"})
        return JsonResponse({"status": "invalid request"}, status=400)
    else:
        # if request is not AJAX, render page
        return render(request, "flashcards/learn.html")

@login_required # if user is not authenticated - page 404
def repeat(request):
    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
    if is_ajax:
        # a word will be displayed to the user at increasing intervals
        # each time the user repeats the word, the interval increases
        # word counts as fully learned if user repeated it 6 times
        intervals = [
            timedelta(minutes=20),
            timedelta(hours=2),
            timedelta(days=1),
            timedelta(days=3),
            timedelta(weeks=1),
            timedelta(weeks=2),
            timedelta(weeks=4)
        ]
        # GET request is used for sending data to js file
        if request.method == "GET":
            word_ids = []
            all_repeat_words = RepeatWord.objects.filter(user=request.user)
            # find words to repeat
            for word in all_repeat_words:
                if word.date + intervals[word.times_repeated] < timezone.now():
                    word_ids.append(word.english_words_id)

            repeat_words = list(EnglishWords.objects.filter(id__in=word_ids).values())
            return JsonResponse({"repeat_words": repeat_words})
        # POST request is used for getting data from js file
        elif request.method == "POST":
            data = json.loads(request.POST.get("main"))
            repeat_word = RepeatWord.objects.filter(user=request.user, english_words = data["word_id"])
            # if user repeated word 6 times, mark it as "fully learned" and remove it from RepeatWord
            if repeat_word[0].times_repeated == 6:
                UserWordSelection.objects.filter(user=request.user, english_words = data["word_id"]).update(status="learned")
                repeat_word.delete()
            # increment times_repeated field and update timer
            else:
                repeat_word.update(times_repeated=F("times_repeated") + 1, date=timezone.now())
            return JsonResponse({"status": "success"})
        else:
            return JsonResponse({"status": "invalid request"}, status=400)
    else:
        # if request is not AJAX, render the page
        return render(request, "flashcards/repeat.html")

flashcards/templates/flashcards/base.html
<!DOCTYPE html> 
<html>
    {% load static %}
<head>
    {% block head %}
    <title>EasyWord</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/svg+xml" href="{% static 'flashcards/images/favicon.svg' %}">
    <link rel="stylesheet" href="{% static 'flashcards/bootstrap-5.3.3/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'flashcards/main.css' %}">
    {% endblock %}
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg bg-info-subtle">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'flashcards:index' %}">EasyWord</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <ul class="nav nav-underline">
                <li class="nav-item">         
                    <a class="nav-link{% if request.path == '/dictionary/' %} active{% endif %}" aria-current="page" href="{% url 'flashcards:dictionary' %}">Словник</a>                          
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'flashcards:learn' %}">Вчити</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'flashcards:repeat' %}">Повторити</a>
                </li>
                {% endif %}
              </ul>
            </ul>
            {% if user.is_authenticated %}
              <a class="btn btn-outline-primary" href = "{% url 'flashcards:logout_user' %}">Вийти</a>
            {% else %}
              <a class="btn btn-outline-primary" href = "{% url 'flashcards:login' %}">Увійти</a>
            {% endif %}
            
          </div>
        </div>
      </nav>
    {% endblock %}

    {% block content %}{% endblock %}

    {% block js %}
    <script src="{% static 'flashcards/bootstrap-5.3.3/js/bootstrap.bundle.min.js' %}"></script>
    {% endblock %}
</body>
</html>

flashcards/templates/flashcards/dictionary.html
<!DOCTYPE html> 
<html>
    {% extends 'flashcards/base.html' %}
    {% load static %}
<head>
</head>

<body>
    {% block content %}           
            <div class="container-fluid">
                <div class="row">                  
                  <div class="col-3 bg-light"></div>                            
                  <div class="col-6">
                    <br>
                    {% for data in english_words %}
                    <p>{{ data.word }} – {{ data.translation}}</p>         
                    {% endfor %}
                
                    <!-- Pagination -->
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                        <!-- link to previous page -->
                        {% if english_words.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{english_words.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}
                        <!-- link to first page -->
                        <li class="page-item{% if 1 == english_words.number %} disabled{% endif %}"><a class="page-link" href="?page=1">1</a></li>

                        <!-- "..." button -->  
                        {% if english_words.number|add:-2 > 2 %}           
                        <li class="page-item"><a class="page-link" href="">...</a></li> 
                        {% endif %}
                        
                        <!-- links to 2 next pages and 2 previous pages -->    
                        {% for i in page_range %}
                            <li class="page-item{% if i == english_words.number %} disabled{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li> 
                        {% endfor %}

                        <!-- "..." button -->  
                        {% if english_words.number|add:3 < english_words.paginator.num_pages %}           
                            <li class="page-item"><a class="page-link" href="">...</a></li> 
                        {% endif %}

                        <!-- link to last page -->
                        <li class="page-item{% if english_words.paginator.num_pages == english_words.number %} disabled{% endif %}"><a class="page-link" href="?page={{english_words.paginator.num_pages}}">{{english_words.paginator.num_pages}}</a></li>
                        <!-- link to next page -->
                        {% if english_words.has_next %}
                        <li class="page-item">                           
                            <a class="page-link" href="?page={{english_words.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                        </ul>
                    </nav>

                </div>
                <div class="col-3 bg-light"></div>
              </div>
    {% endblock %}
</body>
</html>

flashcards/templates/flashcards/index.html
<!DOCTYPE html> 
<html>
    {% extends 'flashcards/base.html' %}
    {% load static %}
<head>
</head>

<body>
</body>
</html>

flashcards/templates/flashcards/learn.html
<!DOCTYPE html> 
<html>
    {% extends 'flashcards/base.html' %}
    {% load static %}
<head>
</head>

<body>
    {% block content %}
    <div class = "container-fluid">
        <div class="row">
        <div class="col-4"></div>
            <div class = "col-4 border rounded shadow-sm mt-5 card">
                <h1 class = "word" id = "word">&nbsp;</h1>
                <p class="text-secondary" id = "phonetics">&nbsp;</p>
                <img src = "{% static 'flashcards/images/sound_speaker_icon.png' %}" alt = "sound speaker icon" class = "sound-speaker-icon" id = "sound-speaker-icon">              
                <audio src="" id = "pronunciation"></audio>
                <hr>
                <div class="show-info">
                    <img src="{% static 'flashcards/images/eye_icon.png' %}" alt = "eye icon" class="eye-icon border border rounded p-3 shadow-sm" id = "eye-icon">
                    <h1 id = "translation"></h1>
                </div>
                    <div class = buttons>
                        <input type="button" value="Я вже знаю це слово" id = "skip-word" class = "btn btn-light">
                        <input type="button" value="Вчити це слово" id = "learn-word" class = "btn btn-light">                       
                    </div>             
            </div>
        <div class="col-4"></div>  
        </div>
    </div>
    {% endblock %}
    {% block js %}
    {% csrf_token %}
    <script src="{% static 'flashcards/bootstrap-5.3.3/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'flashcards/learn.js' %}"></script> 
    {% endblock %}
</body>
</html>

flashcards/templates/flashcards/login.html
<!DOCTYPE html> 
<html>
    {% extends 'flashcards/base.html' %}
    {% load static %}
<head>
</head>

<body>
    {% block content %}
    <div class = "container-fluid">
        <div class="row">
        <div class="col-4"></div>
            <div class = "col-4 p-4 border rounded shadow-sm mt-5">
                <h1 class="text-center">Увійти</h1>             
                <form method="post">
                    {% csrf_token %}                
                    {% for element in form %}
                        <div class = "mb-3">
                            <label for="{{element.id_for_label}}" class="form-label">{{ element.label_tag }}</label>   
                            {{element}}
                        </div>
                    {% endfor %}
                    
                    {% if form.errors %}
                        <ul class="errorlist">
                            <li class = "text-danger">Ім'я користувача або пароль було введено неправильно.</li>
                        </ul>
                    {% endif %}
                    
                    <button type="submit" class = "btn btn-primary mx-auto d-block mt-3">Увійти</button>
                </form>
                <br>
                <a href="{%url 'flashcards:register'%}">Немає акунта? Зареєструйтесь!</a>
            </div>
        <div class="col-4"></div>  
        </div>
    </div>
    {% endblock %}
</body>
</html>

flashcards/templates/flashcards/register.html
<!DOCTYPE html> 
<html>
    {% extends 'flashcards/base.html' %}
    {% load static %}
<head>
</head>

<body>
    {% block content %}
    <div class = "container-fluid">
        <div class="row">
            <div class="col-4"></div>  
                <div class = "col-4 p-4 border rounded shadow-sm mt-5">
                    <h1 class="text-center">Реєстрація</h1>
                    <form method="post">
                        {% csrf_token %}
                        {% for element in form %}
                            <div class="mb-3">                         
                                <label for="{{element.id_for_label}}" class="form-label">{{ element.label_tag }}</label>
                                {{element}}
                                <ul class="errorlist">
                                    {% for error in element.errors %}
                                        <li class = "text-danger">{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary mx-auto d-block">Зареєструватися</button>                      
                    </form>
                </div>

            <div class="col-4"></div>  
        </div>
    </div>
    
    {% endblock %}
</body>
</html>

flashcards/templates/flashcards/repeat.html
<!DOCTYPE html> 
<html>
    {% extends 'flashcards/base.html' %}
    {% load static %}
<head>
</head>

<body>
    {% block content %}
    {% csrf_token %}
    <div class = "container-fluid">
        <div class="row">
        <div class="col-4"></div>
            <div class = "col-4 border rounded shadow-sm mt-5 card">
                <h1 class = "word" id = "word">&nbsp;</h1>
                <hr>
                <div class="show-info">
                    <img src="{% static 'flashcards/images/eye_icon.png' %}" alt = "eye icon" class="eye-icon border border rounded p-3 shadow-sm" id = "eye-icon">
                    <h1 id = "translation"></h1>
                    <p class="text-secondary" id = "phonetics">&nbsp;</p>
                    <img src = "{% static 'flashcards/images/sound_speaker_icon.png' %}" alt = "sound speaker icon" class = "sound-speaker-icon" id = "sound-speaker-icon">              
                    <audio src="" id = "pronunciation"></audio>
                </div>
                    <div class = "buttons">
                        <input type="button" value="Пам'ятаю" id = "remember-word" class = "btn btn-light">
                        <input type="button" value="Не пам'ятаю" id = "dont-remember-word" class = "btn btn-light">                       
                    </div>             
            </div>
        <div class="col-4"></div>  
        </div>
    </div>
    {% endblock %}

    {% block js %}
    <script src="{% static 'flashcards/bootstrap-5.3.3/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'flashcards/repeat.js' %}"></script> 
    {% endblock %}
</body>
</html>